<?php

namespace Database\Seeders;

use App\Models\CountrieModel;
use Illuminate\Database\Seeder;

use Illuminate\Support\Facades\DB;
use App\Services\SlgGenrateService;
use App\Models\Countrie\CountrieModels;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        CountrieModel::truncate();

        $countries_completed = [
            [
                'countrie_name' => "Côte d'Ivoire",
                'countrie_flag' => "🇨🇮",
                'countrie_iso_code' => "CI",
                'countrie_phone_code' => "225",
                'countrie_currency' => "XOF",
                'nationality' => "Ivoirienne",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Burkina Faso",
                'countrie_flag' => "🇧🇫",
                'countrie_iso_code' => "BF",
                'countrie_phone_code' => "226",
                'countrie_currency' => "XOF",
                'nationality' => "Burkinabé",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Mali",
                'countrie_flag' => "🇲🇱",
                'countrie_iso_code' => "ML",
                'countrie_phone_code' => "223",
                'countrie_currency' => "XOF",
                'nationality' => "Malienne",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Tchad",
                'countrie_flag' => "🇹🇩",
                'countrie_iso_code' => "TD",
                'countrie_phone_code' => "235",
                'countrie_currency' => "XAF",
                'nationality' => "Tchadienne",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "République Centrafricaine",
                'countrie_flag' => "🇨🇫",
                'countrie_iso_code' => "CF",
                'countrie_phone_code' => "236",
                'countrie_currency' => "XAF",
                'nationality' => "Centrafricaine",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Guinée Equatoriale",
                'countrie_flag' => "🇬🇶",
                'countrie_iso_code' => "GQ",
                'countrie_phone_code' => "240",
                'countrie_currency' => "XAF",
                'nationality' => "Equato-Guinéen",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Guinée",
                'countrie_flag' => "🇬🇳",
                'countrie_iso_code' => "GN",
                'countrie_phone_code' => "224",
                'countrie_currency' => "GNF",
                'nationality' => "Guinéen",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Comores",
                'countrie_flag' => "🇰🇲",
                'countrie_iso_code' => "KM",
                'countrie_phone_code' => "269",
                'countrie_currency' => "KMF",
                'nationality' => "Comorien",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Ghana",
                'countrie_flag' => "🇬🇭",
                'countrie_iso_code' => "GH",
                'countrie_phone_code' => "233",
                'countrie_currency' => "GHS",
                'nationality' => "Ghanéen",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Gambie",
                'countrie_flag' => "🇬🇲",
                'countrie_iso_code' => "GM",
                'countrie_phone_code' => "220",
                'countrie_currency' => "GMD",
                'nationality' => "Gambien",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Nigeria",
                'countrie_flag' => "🇳🇬",
                'countrie_iso_code' => "NG",
                'countrie_phone_code' => "234",
                'countrie_currency' => "NGN",
                'nationality' => "Nigérian",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Niger",
                'countrie_flag' => "🇳🇪",
                'countrie_iso_code' => "NE",
                'countrie_phone_code' => "227",
                'countrie_currency' => "XOF",
                'nationality' => "Nigerien",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Sierra Leone",
                'countrie_flag' => "🇸🇱",
                'countrie_iso_code' => "SL",
                'countrie_phone_code' => "232",
                'countrie_currency' => "SLL",
                'nationality' => "Sierra-Léonais",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Mauritanie",
                'countrie_flag' => "🇲🇷",
                'countrie_iso_code' => "MR",
                'countrie_phone_code' => "222",
                'countrie_currency' => "MRO",
                'nationality' => "Mauritanien",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Sénégal",
                'countrie_flag' => "🇸🇳",
                'countrie_iso_code' => "SN",
                'countrie_phone_code' => "221",
                'countrie_currency' => "XOF",
                'nationality' => "Sénégalais",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Congo-Brazzaville",
                'countrie_flag' => "🇨🇬",
                'countrie_iso_code' => "CG",
                'countrie_phone_code' => "242",
                'countrie_currency' => "XAF",
                'nationality' => "Congolais",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Congo-Kinshasa",
                'countrie_flag' => "🇨🇩",
                'countrie_iso_code' => "CD",
                'countrie_phone_code' => "243",
                'countrie_currency' => "CDF",
                'nationality' => "Congolais",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Djibouti",
                'countrie_flag' => "🇩🇯",
                'countrie_iso_code' => "DJ",
                'countrie_phone_code' => "253",
                'countrie_currency' => "DJF",
                'nationality' => "Djiboutien",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Rwanda",
                'countrie_flag' => "🇷🇼",
                'countrie_iso_code' => "RW",
                'countrie_phone_code' => "250",
                'countrie_currency' => "RWF",
                'nationality' => "Rwandais",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Soudan",
                'countrie_flag' => "🇸🇩",
                'countrie_iso_code' => "SD",
                'countrie_phone_code' => "249",
                'countrie_currency' => "SDG",
                'nationality' => "Soudanais",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Tanzanie",
                'countrie_flag' => "🇹🇿",
                'countrie_iso_code' => "TZ",
                'countrie_phone_code' => "255",
                'countrie_currency' => "TZS",
                'nationality' => "Tanzanien",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Zambie",
                'countrie_flag' => "🇿🇲",
                'countrie_iso_code' => "ZM",
                'countrie_phone_code' => "260",
                'countrie_currency' => "ZMW",
                'nationality' => "Zambien",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Zimbabwe",
                'countrie_flag' => "🇿🇼",
                'countrie_iso_code' => "ZW",
                'countrie_phone_code' => "263",
                'countrie_currency' => "ZWL",
                'nationality' => "Zimbabwéen",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Zimbabwe",
                'countrie_flag' => "🇿🇼",
                'countrie_iso_code' => "ZW",
                'countrie_phone_code' => "263",
                'countrie_currency' => "ZWL",
                'nationality' => "Zimbabwean",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Mozambique",
                'countrie_flag' => "🇲🇿",
                'countrie_iso_code' => "MZ",
                'countrie_phone_code' => "258",
                'countrie_currency' => "MZN",
                'nationality' => "Mozambican",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Zambie",
                'countrie_flag' => "🇿🇲",
                'countrie_iso_code' => "ZM",
                'countrie_phone_code' => "260",
                'countrie_currency' => "ZMW",
                'nationality' => "Zambian",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Soudan du sud",
                'countrie_flag' => "🇸🇸",
                'countrie_iso_code' => "SS",
                'countrie_phone_code' => "211",
                'countrie_currency' => "SSP",
                'nationality' => "South Sudanese",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Soudan",
                'countrie_flag' => "🇸🇩",
                'countrie_iso_code' => "SD",
                'countrie_phone_code' => "249",
                'countrie_currency' => "SDG",
                'nationality' => "Sudanese",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Algérie",
                'countrie_flag' => "🇩🇿",
                'countrie_iso_code' => "DZ",
                'countrie_phone_code' => "213",
                'countrie_currency' => "DZD",
                'nationality' => "Algerian",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Erythrée",
                'countrie_flag' => "🇪🇷",
                'countrie_iso_code' => "ER",
                'countrie_phone_code' => "291",
                'countrie_currency' => "ERN",
                'nationality' => "Eritrean",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Angola",
                'countrie_flag' => "🇦🇴",
                'countrie_iso_code' => "AO",
                'countrie_phone_code' => "244",
                'countrie_currency' => "AOA",
                'nationality' => "Angolan",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Bénin",
                'countrie_flag' => "🇧🇯",
                'countrie_iso_code' => "BJ",
                'countrie_phone_code' => "229",
                'countrie_currency' => "XOF",
                'nationality' => "Beninese",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Botswana",
                'countrie_flag' => "🇧🇼",
                'countrie_iso_code' => "BW",
                'countrie_phone_code' => "267",
                'countrie_currency' => "BWP",
                'nationality' => "Botswanan",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Burundi",
                'countrie_flag' => "🇧🇮",
                'countrie_iso_code' => "BI",
                'countrie_phone_code' => "257",
                'countrie_currency' => "BIF",
                'nationality' => "Burundais",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],[
                'countrie_name' => "Cameroun",
                'countrie_flag' => "🇨🇲",
                'countrie_iso_code' => "CM",
                'countrie_phone_code' => "237",
                'countrie_currency' => "XAF",
                'nationality' => "Camerounais",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],[
                'countrie_name' => "Cap-Vert",
                'countrie_flag' => "🇨🇻",
                'countrie_iso_code' => "CV",
                'countrie_phone_code' => "238",
                'countrie_currency' => "CVE",
                'nationality' => "Capverdien",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],[
                'countrie_name' => "Congo",
                'countrie_flag' => "🇨🇬",
                'countrie_iso_code' => "CG",
                'countrie_phone_code' => "242",
                'countrie_currency' => "XAF",
                'nationality' => "Congolais",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],[
                'countrie_name' => "RD Congo",
                'countrie_flag' => "🇨🇩",
                'countrie_iso_code' => "CD",
                'countrie_phone_code' => "243",
                'countrie_currency' => "CDF",
                'nationality' => "Congolais",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],[
                'countrie_name' => "Djibouti",
                'countrie_flag' => "🇩🇯",
                'countrie_iso_code' => "DJ",
                'countrie_phone_code' => "253",
                'countrie_currency' => "DJF",
                'nationality' => "Djiboutien",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],[
                'countrie_name' => "Égypte",
                'countrie_flag' => "🇪🇬",
                'countrie_iso_code' => "EG",
                'countrie_phone_code' => "20",
                'countrie_currency' => "EGP",
                'nationality' => "Égyptien",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],[
                'countrie_name' => "Éthiopie",
                'countrie_flag' => "🇪🇹",
                'countrie_iso_code' => "ET",
                'countrie_phone_code' => "251",
                'countrie_currency' => "ETB",
                'nationality' => "Éthiopien",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],[
                'countrie_name' => "Gabon",
                'countrie_flag' => "🇬🇦",
                'countrie_iso_code' => "GA",
                'countrie_phone_code' => "241",
                'countrie_currency' => "XAF",
                'nationality' => "Gabonais",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Guinée-Bissau",
                'countrie_flag' => "🇬🇼",
                'countrie_iso_code' => "GW",
                'countrie_phone_code' => "245",
                'countrie_currency' => "XOF",
                'nationality' => "Guinéen",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Kenya",
                'countrie_flag' => "🇰🇪",
                'countrie_iso_code' => "KE",
                'countrie_phone_code' => "254",
                'countrie_currency' => "KES",
                'nationality' => "Kényan",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Lesotho",
                'countrie_flag' => "🇱🇸",
                'countrie_iso_code' => "LS",
                'countrie_phone_code' => "266",
                'countrie_currency' => "LSL",
                'nationality' => "Lesothan",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Liberia",
                'countrie_flag' => "🇱🇷",
                'countrie_iso_code' => "LR",
                'countrie_phone_code' => "231",
                'countrie_currency' => "LRD",
                'nationality' => "Libérien",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Libye",
                'countrie_flag' => "🇱🇾",
                'countrie_iso_code' => "LY",
                'countrie_phone_code' => "218",
                'countrie_currency' => "LYD",
                'nationality' => "Libyen",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Madagascar",
                'countrie_flag' => "🇲🇬",
                'countrie_iso_code' => "MG",
                'countrie_phone_code' => "261",
                'countrie_currency' => "MGA",
                'nationality' => "Malgache",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Malawi",
                'countrie_flag' => "🇲🇼",
                'countrie_iso_code' => "MW",
                'countrie_phone_code' => "265",
                'countrie_currency' => "MWK",
                'nationality' => "Malawien",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Maroc",
                'countrie_flag' => "🇲🇦",
                'countrie_iso_code' => "MA",
                'countrie_phone_code' => "212",
                'countrie_currency' => "MAD",
                'nationality' => "Marocain",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Mozambique",
                'countrie_flag' => "🇲🇿",
                'countrie_iso_code' => "MZ",
                'countrie_phone_code' => "258",
                'countrie_currency' => "MZN",
                'nationality' => "Mozambicain",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Namibie",
                'countrie_flag' => "🇳🇦",
                'countrie_iso_code' => "NA",
                'countrie_phone_code' => "264",
                'countrie_currency' => "NAD",
                'nationality' => "Namibien",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Rwanda",
                'countrie_flag' => "🇷🇼",
                'countrie_iso_code' => "RW",
                'countrie_phone_code' => "250",
                'countrie_currency' => "RWF",
                'nationality' => "Rwandais",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Sao Tomé et principe",
                'countrie_flag' => "🇸🇹",
                'countrie_iso_code' => "ST",
                'countrie_phone_code' => "239",
                'countrie_currency' => "STD",
                'nationality' => "Sao-toméen",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],[
                'countrie_name' => "Sénégal",
                'countrie_flag' => "🇸🇳",
                'countrie_iso_code' => "SN",
                'countrie_phone_code' => "221",
                'countrie_currency' => "XOF",
                'nationality' => "Sénégalais",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Somalie",
                'countrie_flag' => "🇸🇴",
                'countrie_iso_code' => "SO",
                'countrie_phone_code' => "252",
                'countrie_currency' => "SOS",
                'nationality' => "Somalien",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Tanzanie",
                'countrie_flag' => "🇹🇿",
                'countrie_iso_code' => "TZ",
                'countrie_phone_code' => "255",
                'countrie_currency' => "TZS",
                'nationality' => "Tanzanien",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Afrique du sud",
                'countrie_flag' => "🇿🇦",
                'countrie_iso_code' => "ZA",
                'countrie_phone_code' => "27",
                'countrie_currency' => "ZAR",
                'nationality' => "Sud-Africain",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Togo",
                'countrie_flag' => "🇹🇬",
                'countrie_iso_code' => "TG",
                'countrie_phone_code' => "228",
                'countrie_currency' => "XOF",
                'nationality' => "Togolais",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Tunisie",
                'countrie_flag' => "🇹🇳",
                'countrie_iso_code' => "TN",
                'countrie_phone_code' => "216",
                'countrie_currency' => "TND",
                'nationality' => "Tunisien",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Ouganda",
                'countrie_flag' => "🇺🇬",
                'countrie_iso_code' => "UG",
                'countrie_phone_code' => "256",
                'countrie_currency' => "UGX",
                'nationality' => "Ougandais",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Seychelles",
                'countrie_flag' => "🇸🇨",
                'countrie_iso_code' => "SC",
                'countrie_phone_code' => "248",
                'countrie_currency' => "SCR",
                'nationality' => "Seychellois",
                'continent' => "Afrique",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Algérie",
                'countrie_flag' => "🇩🇿",
                'continent' => 'Afrique',
                'countrie_iso_code' => "DZ",
                'countrie_phone_code' => "213",
                'countrie_currency' => "DZD",
                'nationality' => "Algérien",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Angola",
                'countrie_flag' => "🇦🇴",
                'continent' => 'Afrique',
                'countrie_iso_code' => "AO",
                'countrie_phone_code' => "244",
                'countrie_currency' => "AOA",
                'nationality' => "Angolais",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Bénin",
                'countrie_flag' => "🇧🇯",
                'continent' => 'Afrique',
                'countrie_iso_code' => "BJ",
                'countrie_phone_code' => "229",
                'countrie_currency' => "XOF",
                'nationality' => "Béninois",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Burkina Faso",
                'countrie_flag' => "🇧🇫",
                'continent' => 'Afrique',
                'countrie_iso_code' => "BF",
                'countrie_phone_code' => "226",
                'countrie_currency' => "XOF",
                'nationality' => "Burkinabé",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Burundi",
                'countrie_flag' => "🇧🇮",
                'continent' => 'Afrique',
                'countrie_iso_code' => "BI",
                'countrie_phone_code' => "257",
                'countrie_currency' => "BIF",
                'nationality' => 'Burundais',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Cabo Verde",
                'countrie_flag' => "🇨🇻",
                'continent' => 'Afrique',
                'countrie_iso_code' => "CV",
                'countrie_phone_code' => "238",
                'countrie_currency' => "CVE",
                'nationality' => 'Capverdien',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Cameroun",
                'countrie_flag' => "🇨🇲",
                'continent' => 'Afrique',
                'countrie_iso_code' => "CM",
                'countrie_phone_code' => "237",
                'countrie_currency' => "XAF",
                'nationality' => 'Camerounais',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "République Centrafricaine",
                'countrie_flag' => "🇨🇫",
                'continent' => 'Afrique',
                'countrie_iso_code' => "CF",
                'countrie_phone_code' => "236",
                'countrie_currency' => "XAF",
                'nationality' => 'Centrafricain',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Chad",
                'countrie_flag' => "🇹🇩",
                'continent' => 'Afrique',
                'countrie_iso_code' => "TD",
                'countrie_phone_code' => "235",
                'countrie_currency' => "XAF",
                'nationality' => 'Tchadien',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Comores",
                'countrie_flag' => "🇰🇲",
                'continent' => 'Afrique',
                'countrie_iso_code' => "KM",
                'countrie_phone_code' => "269",
                'countrie_currency' => "KMF",
                'nationality' => 'Comorien',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Congo-Brazzaville",
                'countrie_flag' => "🇨🇬",
                'continent' => 'Afrique',
                'countrie_iso_code' => "CG",
                'countrie_phone_code' => "242",
                'countrie_currency' => "XAF",
                'nationality' => 'Congolais',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Congo-Kinshasa",
                'countrie_flag' => "🇨🇩",
                'continent' => 'Afrique',
                'countrie_iso_code' => "CD",
                'countrie_phone_code' => "243",
                'countrie_currency' => "CDF",
                'nationality' => 'Congolais',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Djibouti",
                'countrie_flag' => "🇩🇯",
                'continent' => 'Afrique',
                'countrie_iso_code' => "DJ",
                'countrie_phone_code' => "253",
                'countrie_currency' => "DJF",
                'nationality' => 'Djiboutien',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Égypte",
                'countrie_flag' => "🇪🇬",
                'continent' => 'Afrique',
                'countrie_iso_code' => "EG",
                'countrie_phone_code' => "20",
                'countrie_currency' => "EGP",
                'nationality' => 'Égyptien',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Érythrée",
                'countrie_flag' => "🇪🇷",
                'continent' => 'Afrique',
                'countrie_iso_code' => "ER",
                'countrie_phone_code' => "291",
                'countrie_currency' => "ERN",
                'nationality' => 'Érythréen',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Eswatini",
                'countrie_flag' => "🇸🇿",
                'continent' => 'Afrique',
                'countrie_iso_code' => "SZ",
                'countrie_phone_code' => "268",
                'countrie_currency' => "SZL",
                'nationality' => 'Eswatinien',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Ethiopie",
                'countrie_flag' => "🇪🇹",
                'continent' => 'Afrique',
                'countrie_iso_code' => "ET",
                'countrie_phone_code' => "251",
                'countrie_currency' => "ETB",
                'nationality' => 'Éthiopien',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Gabon",
                'countrie_flag' => "🇬🇦",
                'continent' => 'Afrique',
                'countrie_iso_code' => "GA",
                'countrie_phone_code' => "241",
                'countrie_currency' => "XAF",
                'nationality' => 'Gabonais',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Gambie",
                'countrie_flag' => "🇬🇲",
                'continent' => 'Afrique',
                'countrie_iso_code' => "GM",
                'countrie_phone_code' => "220",
                'countrie_currency' => "GMD",
                'nationality' => 'Gambien',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Ghana",
                'countrie_flag' => "🇬🇭",
                'continent' => 'Afrique',
                'countrie_iso_code' => "GH",
                'countrie_phone_code' => "233",
                'countrie_currency' => "GHS",
                'nationality' => 'Ghanéen',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Guinée",
                'countrie_flag' => "🇬🇳",
                'continent' => 'Afrique',
                'countrie_iso_code' => "GN",
                'countrie_phone_code' => "224",
                'countrie_currency' => "GNF",
                'nationality' => 'Guinéen',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Guinée-Bissau",
                'countrie_flag' => "🇬🇼",
                'continent' => 'Afrique',
                'countrie_iso_code' => "GW",
                'countrie_phone_code' => "245",
                'countrie_currency' => "XOF",
                'nationality' => 'Bissau-Guinéen',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Kenya",
                'countrie_flag' => "🇰🇪",
                'continent' => 'Afrique',
                'countrie_iso_code' => "KE",
                'countrie_phone_code' => "254",
                'countrie_currency' => "KES",
                'nationality' => 'Kényan',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Lesotho",
                'countrie_flag' => "🇱🇸",
                'continent' => 'Afrique',
                'countrie_iso_code' => "LS",
                'countrie_phone_code' => "266",
                'countrie_currency' => "LSL",
                'nationality' => 'Lesothan',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Liberia",
                'countrie_flag' => "🇱🇷",
                'continent' => 'Afrique',
                'countrie_iso_code' => "LR",
                'countrie_phone_code' => "231",
                'countrie_currency' => "LRD",
                'nationality' => 'Libérien',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Libye",
                'countrie_flag' => "🇱🇾",
                'continent' => 'Afrique',
                'countrie_iso_code' => "LY",
                'countrie_phone_code' => "218",
                'countrie_currency' => "LYD",
                'nationality' => 'Libyen',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Madagascar",
                'countrie_flag' => "🇲🇬",
                'continent' => 'Afrique',
                'countrie_iso_code' => "MG",
                'countrie_phone_code' => "261",
                'countrie_currency' => "MGA",
                'nationality' => 'Malgache',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Malawi",
                'countrie_flag' => "🇲🇼",
                'continent' => 'Afrique',
                'countrie_iso_code' => "MW",
                'countrie_phone_code' => "265",
                'countrie_currency' => "MWK",
                'nationality' => 'Malawien',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Mali",
                'countrie_flag' => "🇲🇱",
                'continent' => 'Afrique',
                'countrie_iso_code' => "ML",
                'countrie_phone_code' => "223",
                'countrie_currency' => "XOF",
                'nationality' => 'Maliens',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Maroc",
                'countrie_flag' => "🇲🇦",
                'continent' => 'Afrique',
                'countrie_iso_code' => "MA",
                'countrie_phone_code' => "212",
                'countrie_currency' => "MAD",
                'nationality' => 'Marocain',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Maurice",
                'countrie_flag' => "🇲🇺",
                'continent' => 'Afrique',
                'countrie_iso_code' => "MU",
                'countrie_phone_code' => "230",
                'countrie_currency' => "MUR",
                'nationality' => 'Mauricien',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Mauritanie",
                'countrie_flag' => "🇲🇱",
                'continent' => 'Afrique',
                'countrie_iso_code' => "MR",
                'countrie_phone_code' => "222",
                'countrie_currency' => "MRU",
                'nationality' => 'Mauritanien',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Mozambique",
                'countrie_flag' => "🇲🇿",
                'continent' => 'Afrique',
                'countrie_iso_code' => "MZ",
                'countrie_phone_code' => "258",
                'countrie_currency' => "MZN",
                'nationality' => 'Mozambicain',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Namibie",
                'countrie_flag' => "🇳🇦",
                'continent' => 'Afrique',
                'countrie_iso_code' => "NA",
                'countrie_phone_code' => "264",
                'countrie_currency' => "NAD",
                'nationality' => 'Namibien',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Niger",
                'countrie_flag' => "🇳🇪",
                'continent' => 'Afrique',
                'countrie_iso_code' => "NE",
                'countrie_phone_code' => "227",
                'countrie_currency' => "XOF",
                'nationality' => 'Nigerien',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Nigeria",
                'countrie_flag' => "🇳🇬",
                'continent' => 'Afrique',
                'countrie_iso_code' => "NG",
                'countrie_phone_code' => "234",
                'countrie_currency' => "NGN",
                'nationality' => 'Nigérian',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Rwanda",
                'countrie_flag' => "🇷🇼",
                'continent' => 'Afrique',
                'countrie_iso_code' => "RW",
                'countrie_phone_code' => "250",
                'countrie_currency' => "RWF",
                'nationality' => 'Rwandais',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Sénégal",
                'countrie_flag' => "🇸🇳",
                'continent' => 'Afrique',
                'countrie_iso_code' => "SN",
                'countrie_phone_code' => "221",
                'countrie_currency' => "XOF",
                'nationality' => 'Sénégalais',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Sierra Leone",
                'countrie_flag' => "🇸🇱",
                'continent' => 'Afrique',
                'countrie_iso_code' => "SL",
                'countrie_phone_code' => "232",
                'countrie_currency' => "SLL",
                'nationality' => 'Sierra-léonais',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Somalie",
                'countrie_flag' => "🇸🇴",
                'continent' => 'Afrique',
                'countrie_iso_code' => "SO",
                'countrie_phone_code' => "252",
                'countrie_currency' => "SOS",
                'nationality' => 'Somalien',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Soudan",
                'countrie_flag' => "🇸🇩",
                'continent' => 'Afrique',
                'countrie_iso_code' => "SD",
                'countrie_phone_code' => "249",
                'countrie_currency' => "SDG",
                'nationality' => 'Soudanais',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Tanzanie",
                'countrie_flag' => "🇹🇿",
                'continent' => 'Afrique',
                'countrie_iso_code' => "TZ",
                'countrie_phone_code' => "255",
                'countrie_currency' => "TZS",
                'nationality' => 'Tanzanien',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Togo",
                'countrie_flag' => "🇹🇬",
                'continent' => 'Afrique',
                'countrie_iso_code' => "TG",
                'countrie_phone_code' => "228",
                'countrie_currency' => "XOF",
                'nationality' => 'Togolais',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Tunisie",
                'countrie_flag' => "🇹🇳",
                'continent' => 'Afrique',
                'countrie_iso_code' => "TN",
                'countrie_phone_code' => "216",
                'countrie_currency' => "TND",
                'nationality' => 'Tunisien',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Uganda",
                'countrie_flag' => "🇺🇬",
                'continent' => 'Afrique',
                'countrie_iso_code' => "UG",
                'countrie_phone_code' => "256",
                'countrie_currency' => "UGX",
                'nationality' => 'Ougandais',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Zambie",
                'countrie_flag' => "🇿🇲",
                'continent' => 'Afrique',
                'countrie_iso_code' => "ZM",
                'countrie_phone_code' => "260",
                'countrie_currency' => "ZMW",
                'nationality' => 'Zambien',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Zimbabwe",
                'countrie_flag' => "🇿🇼",
                'continent' => 'Afrique',
                'countrie_iso_code' => "ZW",
                'countrie_phone_code' => "263",
                'countrie_currency' => "ZWL",
                'nationality' => 'Zimbabwéen',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],[
                'countrie_name' => 'Albanie',
                'countrie_flag' => '🇦🇱',
                'continent' => 'Europe',
                'countrie_iso_code' => 'AL',
                'countrie_phone_code' => '355',
                'countrie_currency' => 'ALL',
                'nationality' => 'Albanais',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => 'Allemagne',
                'countrie_flag' => '🇩🇪',
                'continent' => 'Europe',
                'countrie_iso_code' => 'DE',
                'countrie_phone_code' => '49',
                'countrie_currency' => 'EUR',
                'nationality' => 'Allemand',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => 'Andorre',
                'countrie_flag' => '🇦🇩',
                'continent' => 'Europe',
                'countrie_iso_code' => 'AD',
                'countrie_phone_code' => '376',
                'countrie_currency' => 'EUR',
                'nationality' => 'Andorran',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => 'Autriche',
                'countrie_flag' => '🇦🇹',
                'continent' => 'Europe',
                'countrie_iso_code' => 'AT',
                'countrie_phone_code' => '43',
                'countrie_currency' => 'EUR',
                'nationality' => 'Autrichien',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => 'Belgique',
                'countrie_flag' => '🇧🇪',
                'continent' => 'Europe',
                'countrie_iso_code' => 'BE',
                'countrie_phone_code' => '32',
                'countrie_currency' => 'EUR',
                'nationality' => 'Belge',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => 'Bulgarie',
                'countrie_flag' => '🇧🇬',
                'continent' => 'Europe',
                'countrie_iso_code' => 'BG',
                'countrie_phone_code' => '359',
                'countrie_currency' => 'BGN',
                'nationality' => 'Bulgare',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => 'Chypre',
                'countrie_flag' => '🇨🇾',
                'continent' => 'Europe',
                'countrie_iso_code' => 'CY',
                'countrie_phone_code' => '357',
                'countrie_currency' => 'EUR',
                'nationality' => 'Chypriote',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => 'Danemark',
                'countrie_flag' => '🇩🇰',
                'continent' => 'Europe',
                'countrie_iso_code' => 'DK',
                'countrie_phone_code' => '45',
                'countrie_currency' => 'DKK',
                'nationality' => 'Danois',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => 'Espagne',
                'countrie_flag' => '🇪🇸',
                'continent' => 'Europe',
                'countrie_iso_code' => 'ES',
                'countrie_phone_code' => '34',
                'countrie_currency' => 'EUR',
                'nationality' => 'Espagnol',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => 'Estonie',
                'countrie_flag' => '🇪🇪',
                'continent' => 'Europe',
                'countrie_iso_code' => 'EE',
                'countrie_phone_code' => '372',
                'countrie_currency' => 'EUR',
                'nationality' => 'Estonien',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => 'Finlande',
                'countrie_flag' => '🇫🇮',
                'continent' => 'Europe',
                'countrie_iso_code' => 'FI',
                'countrie_phone_code' => '358',
                'countrie_currency' => 'EUR',
                'nationality' => 'Finlandais',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => 'France',
                'countrie_flag' => '🇫🇷',
                'continent' => 'Europe',
                'countrie_iso_code' => 'FR',
                'countrie_phone_code' => '33',
                'countrie_currency' => 'EUR',
                'nationality' => 'Français',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => 'Grece',
                'countrie_flag' => '🇬🇷',
                'continent' => 'Europe',
                'countrie_iso_code' => 'GR',
                'countrie_phone_code' => '30',
                'countrie_currency' => 'EUR',
                'nationality' => 'Grec',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => 'Hongrie',
                'countrie_flag' => '🇭🇺',
                'continent' => 'Europe',
                'countrie_iso_code' => 'HU',
                'countrie_phone_code' => '36',
                'countrie_currency' => 'HUF',
                'nationality' => 'Hongrois',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => 'Irlande',
                'countrie_flag' => '🇮🇪',
                'continent' => 'Europe',
                'countrie_iso_code' => 'IE',
                'countrie_phone_code' => '353',
                'countrie_currency' => 'EUR',
                'nationality' => 'Irlandais',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => 'Islande',
                'countrie_flag' => '🇮🇸',
                'continent' => 'Europe',
                'countrie_iso_code' => 'IS',
                'countrie_phone_code' => '354',
                'countrie_currency' => 'ISK',
                'nationality' => 'Islandais',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => 'Italie',
                'countrie_flag' => '🇮🇹',
                'continent' => 'Europe',
                'countrie_iso_code' => 'IT',
                'countrie_phone_code' => '39',
                'countrie_currency' => 'EUR',
                'nationality' => 'Italien',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => 'Lettonie',
                'countrie_flag' => '🇱🇻',
                'continent' => 'Europe',
                'countrie_iso_code' => 'LV',
                'countrie_phone_code' => '371',
                'countrie_currency' => 'EUR',
                'nationality' => 'Letton',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => 'Lituanie',
                'countrie_flag' => '🇱🇹',
                'continent' => 'Europe',
                'countrie_iso_code' => 'LT',
                'countrie_phone_code' => '370',
                'countrie_currency' => 'EUR',
                'nationality' => 'Lituanien',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => 'Luxembourg',
                'countrie_flag' => '🇱🇺',
                'continent' => 'Europe',
                'countrie_iso_code' => 'LU',
                'countrie_phone_code' => '352',
                'countrie_currency' => 'EUR',
                'nationality' => 'Luxembourgeois',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => 'Malte',
                'countrie_flag' => '🇲🇹',
                'continent' => 'Europe',
                'countrie_iso_code' => 'MT',
                'countrie_phone_code' => '356',
                'countrie_currency' => 'EUR',
                'nationality' => 'Maltais',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => 'Monaco',
                'countrie_flag' => '🇲🇨',
                'continent' => 'Europe',
                'countrie_iso_code' => 'MC',
                'countrie_phone_code' => '377',
                'countrie_currency' => 'EUR',
                'nationality' => 'Monégasque',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => 'Norvege',
                'countrie_flag' => '🇳🇴',
                'continent' => 'Europe',
                'countrie_iso_code' => 'NO',
                'countrie_phone_code' => '47',
                'countrie_currency' => 'NOK',
                'nationality' => 'Norvégien',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => 'Pays-Bas',
                'countrie_flag' => '🇳🇱',
                'continent' => 'Europe',
                'countrie_iso_code' => 'NL',
                'countrie_phone_code' => '31',
                'countrie_currency' => 'EUR',
                'nationality' => 'Néerlandais',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => 'Pologne',
                'countrie_flag' => '🇵🇱',
                'continent' => 'Europe',
                'countrie_iso_code' => 'PL',
                'countrie_phone_code' => '48',
                'countrie_currency' => 'PLN',
                'nationality' => 'Polonais',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => 'Portugal',
                'countrie_flag' => '🇵🇹',
                'continent' => 'Europe',
                'countrie_iso_code' => 'PT',
                'countrie_phone_code' => '351',
                'countrie_currency' => 'EUR',
                'nationality' => 'Portugais',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => 'République tcheque',
                'countrie_flag' => '🇨🇿',
                'continent' => 'Europe',
                'countrie_iso_code' => 'CZ',
                'countrie_phone_code' => '420',
                'countrie_currency' => 'CZK',
                'nationality' => 'Tcheque',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => 'Roumanie',
                'countrie_flag' => '🇷🇴',
                'continent' => 'Europe',
                'countrie_iso_code' => 'RO',
                'countrie_phone_code' => '40',
                'countrie_currency' => 'RON',
                'nationality' => 'Roumain(e)',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => 'Slovaquie',
                'countrie_flag' => '🇸🇰',
                'continent' => 'Europe',
                'countrie_iso_code' => 'SK',
                'countrie_phone_code' => '421',
                'countrie_currency' => 'EUR',
                'nationality' => 'Slovaque',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => 'Slovénie',
                'countrie_flag' => '🇸🇮',
                'continent' => 'Europe',
                'countrie_iso_code' => 'SI',
                'countrie_phone_code' => '386',
                'countrie_currency' => 'EUR',
                'nationality' => 'Slovene',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => 'Suede',
                'countrie_flag' => '🇸🇪',
                'continent' => 'Europe',
                'countrie_iso_code' => 'SE',
                'countrie_phone_code' => '46',
                'countrie_currency' => 'SEK',
                'nationality' => 'Suédois(e)',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => 'Suisse',
                'countrie_flag' => '🇨🇭',
                'continent' => 'Europe',
                'countrie_iso_code' => 'CH',
                'countrie_phone_code' => '41',
                'countrie_currency' => 'CHF',
                'nationality' => 'Suisse',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => 'Ukraine',
                'countrie_flag' => '🇺🇦',
                'continent' => 'Europe',
                'countrie_iso_code' => 'UA',
                'countrie_phone_code' => '380',
                'countrie_currency' => 'UAH',
                'nationality' => 'Ukrainien(ne)',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => 'Royaume-Uni',
                'countrie_flag' => '🇬🇧',
                'continent' => 'Europe',
                'countrie_iso_code' => 'GB',
                'countrie_phone_code' => '44',
                'countrie_currency' => 'GBP',
                'nationality' => 'Britannique',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "États-Unis",
                'countrie_flag' => "🇺🇸",
                'continent' => 'Amérique',
                'countrie_iso_code' => "US",
                'countrie_phone_code' => "1",
                'countrie_currency' => "USD",
                'nationality' => 'Américain(e)',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Canada",
                'countrie_flag' => "🇨🇦",
                'continent' => 'Amérique',
                'countrie_iso_code' => "CA",
                'countrie_phone_code' => "1",
                'countrie_currency' => "CAD",
                'nationality' => 'Canadien(ne)',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Mexique",
                'countrie_flag' => "🇲🇽",
                'continent' => 'Amérique',
                'countrie_iso_code' => "MX",
                'countrie_phone_code' => "52",
                'countrie_currency' => "MXN",
                'nationality' => 'Mexicain(e)',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Brésil",
                'countrie_flag' => "🇧🇷",
                'continent' => 'Amérique',
                'countrie_iso_code' => "BR",
                'countrie_phone_code' => "55",
                'countrie_currency' => "BRL",
                'nationality' => 'Brésilien(ne)',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Argentine",
                'countrie_flag' => "🇦🇷",
                'continent' => 'Amérique',
                'countrie_iso_code' => "AR",
                'countrie_phone_code' => "54",
                'countrie_currency' => "ARS",
                'nationality' => "Argentin",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Colombie",
                'countrie_flag' => "🇨🇴",
                'continent' => 'Amérique',
                'countrie_iso_code' => "CO",
                'countrie_phone_code' => "57",
                'countrie_currency' => "COP",
                'nationality' => "Colombien",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Venezuela",
                'countrie_flag' => "🇻🇪",
                'continent' => 'Amérique',
                'countrie_iso_code' => "VE",
                'countrie_phone_code' => "58",
                'countrie_currency' => "VES",
                'nationality' => "Vénézuélien",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Chili",
                'countrie_flag' => "🇨🇱",
                'continent' => 'Amérique',
                'countrie_iso_code' => "CL",
                'countrie_phone_code' => "56",
                'countrie_currency' => "CLP",
                'nationality' => "Chilien",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Pérou",
                'countrie_flag' => "🇵🇪",
                'continent' => 'Amérique',
                'countrie_iso_code' => "PE",
                'countrie_phone_code' => "51",
                'countrie_currency' => "PEN",
                'nationality' => "Péruvien",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Équateur",
                'countrie_flag' => "🇪🇨",
                'continent' => 'Amérique',
                'countrie_iso_code' => "EC",
                'countrie_phone_code' => "593",
                'countrie_currency' => "USD",
                'nationality' => "Équatorien",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Bolivie",
                'countrie_flag' => "🇧🇴",
                'continent' => 'Amérique',
                'countrie_iso_code' => "BO",
                'countrie_phone_code' => "591",
                'countrie_currency' => "BOB",
                'nationality' => "Bolivien",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Paraguay",
                'countrie_flag' => "🇵🇾",
                'continent' => 'Amérique',
                'countrie_iso_code' => "PY",
                'countrie_phone_code' => "595",
                'countrie_currency' => "PYG",
                'nationality' => "Paraguayen",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Uruguay",
                'countrie_flag' => "🇺🇾",
                'continent' => 'Amérique',
                'countrie_iso_code' => "UY",
                'countrie_phone_code' => "598",
                'countrie_currency' => "UYU",
                'nationality' => "Uruguayen",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Cuba",
                'countrie_flag' => "🇨🇺",
                'continent' => 'Amérique',
                'countrie_iso_code' => "CU",
                'countrie_phone_code' => "53",
                'countrie_currency' => "CUP",
                'nationality' => "Cuban",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "République Dominicaine",
                'countrie_flag' => "🇩🇴",
                'continent' => 'Amérique',
                'countrie_iso_code' => "DO",
                'countrie_phone_code' => "1",
                'countrie_currency' => "DOP",
                'nationality' => "Dominicain",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Honduras",
                'countrie_flag' => "🇭🇳",
                'continent' => 'Amérique',
                'countrie_iso_code' => "HN",
                'countrie_phone_code' => "504",
                'countrie_currency' => "HNL",
                'nationality' => "Hondurien",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Nicaragua",
                'countrie_flag' => "🇳🇮",
                'continent' => 'Amérique',
                'countrie_iso_code' => "NI",
                'countrie_phone_code' => "505",
                'countrie_currency' => "NIO",
                'nationality' => "Nicaraguayen",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Costa Rica",
                'countrie_flag' => "🇨🇷",
                'continent' => 'Amérique',
                'countrie_iso_code' => "CR",
                'countrie_phone_code' => "506",
                'countrie_currency' => "CRC",
                'nationality' => "Costaricien",
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Panama",
                'countrie_flag' => "🇵🇦",
                'countrie_iso_code' => "PA",
                'countrie_phone_code' => "507",
                'countrie_currency' => "PAB",
                'nationality' => "Panaméenne",
                'continent' => 'Amérique',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "El Salvador",
                'countrie_flag' => "🇸🇻",
                'countrie_iso_code' => "SV",
                'countrie_phone_code' => "503",
                'countrie_currency' => "USD",
                'nationality' => "Salvadorienne",
                'continent' => 'Amérique',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Guatemala",
                'countrie_flag' => "🇬🇹",
                'countrie_iso_code' => "GT",
                'countrie_phone_code' => "502",
                'countrie_currency' => "GTQ",
                'nationality' => "Guatémalteque",
                'continent' => 'Amérique',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Jamaïque",
                'countrie_flag' => "🇯🇲",
                'countrie_iso_code' => "JM",
                'countrie_phone_code' => "1",
                'countrie_currency' => "JMD",
                'nationality' => "Jamaïcaine",
                'continent' => 'Amérique',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Trinité-et-Tobago",
                'countrie_flag' => "🇹🇹",
                'countrie_iso_code' => "TT",
                'countrie_phone_code' => "1",
                'countrie_currency' => "TTD",
                'nationality' => "Trinidadienne",
                'continent' => 'Amérique',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ],
            [
                'countrie_name' => "Barbade",
                'countrie_flag' => "🇧🇧",
                'countrie_iso_code' => "BB",
                'countrie_phone_code' => "1",
                'countrie_currency' => "BBD",
                'nationality' => "Barbadienne",
                'continent' => 'Amérique',
                'slug' => SlgGenrateService::slgGenerate(),
                'created_at' => date("Y-m-d H:i:s", strtotime(now())),
                'updated_at' => date("Y-m-d H:i:s", strtotime(now()))
            ]
        ];

        $countries = collect($countries_completed)->unique('countrie_iso_code')->values()->all();
        foreach($countries as $item) {
            DB::table('countrie_models')->insert($item);
        }

        // foreach($data2 as $item) {
        //     DB::table('countrie_models')->insert($item);
        // }
    }
}
